//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTests.TestServiceBPM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestServiceBPM.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestService", ReplyAction="http://tempuri.org/IService/TestServiceResponse")]
        string TestService(string statusName, string statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestService", ReplyAction="http://tempuri.org/IService/TestServiceResponse")]
        System.Threading.Tasks.Task<string> TestServiceAsync(string statusName, string statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestService2", ReplyAction="http://tempuri.org/IService/TestService2Response")]
        string TestService2(string statusName, string statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestService2", ReplyAction="http://tempuri.org/IService/TestService2Response")]
        System.Threading.Tasks.Task<string> TestService2Async(string statusName, string statusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : NewTests.TestServiceBPM.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<NewTests.TestServiceBPM.IService>, NewTests.TestServiceBPM.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestService(string statusName, string statusId) {
            return base.Channel.TestService(statusName, statusId);
        }
        
        public System.Threading.Tasks.Task<string> TestServiceAsync(string statusName, string statusId) {
            return base.Channel.TestServiceAsync(statusName, statusId);
        }
        
        public string TestService2(string statusName, string statusId) {
            return base.Channel.TestService2(statusName, statusId);
        }
        
        public System.Threading.Tasks.Task<string> TestService2Async(string statusName, string statusId) {
            return base.Channel.TestService2Async(statusName, statusId);
        }
    }
}
